### ISSUE TITLE
[Bug] Write Reusable JavaScript with Functions

### ISSUE THREAD

**Issue by S1ngS1ng** [huluoyang/learn#4]
## Needs to update description and test

Link: https://learn.freecodecamp.one/javascript-algorithms-and-data-structures/basic-javascript/write-reusable-javascript-with-functions

Scope: https://github.com/huluoyang/learn/blob/master/curriculum/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L2330-L2356

Original: https://github.com/freeCodeCamp/curriculum/blob/dev/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L2993

**Comment by huluoyang** [comment]
Thanks for pointed out this. I've fixed it.
